blank_issues_enabled: false
contact_links:
  - name: Portkey Support
    url: https://portkey.ai/docs
    about: Please check our docs before opening an issue
  - name: Discord Community
    url: https://portkey.wiki/community
    about: Ask questions and chat with the community
